# --- Mock Data & Setup ---

# 1. Create a dummy dataset
mock_adlb <- data.frame(
  AVISIT = rep(c(0, 4, 8), each = 4),
  AVAL = c(
    10, 12, 11, 13, # Visit 0
    14, 15, 14, 16, # Visit 4
    18, 19, 17, 20 # Visit 8
  ),
  ARM = rep(c("Trt A", "Trt B"), times = 6)
)

# 2. Create a properly classed base plot (Mocking gg_lineplot output)
p_valid <- ggplot2::ggplot(mock_adlb, ggplot2::aes(x = AVISIT, y = AVAL, colour = ARM)) +
  ggplot2::geom_line() +
  ggplot2::geom_point()
class(p_valid) <- c("crane_gg_line", class(p_valid))

# 3. Create a non-classed base plot to test warnings
p_invalid_class <- ggplot2::ggplot(mock_adlb, ggplot2::aes(x = AVISIT, y = AVAL, colour = ARM)) +
  ggplot2::geom_line()

# 4. Create an empty plot to test missing variable aborts
p_empty <- ggplot2::ggplot()
class(p_empty) <- c("crane_gg_line", class(p_empty))


# --- Tests ---

test_that("annotate_lineplot_df warns if plot is not generated by gg_lineplot", {
  # Expect the specific cli_warn message
  expect_warning(
    annotate_lineplot_df(gg_plt = p_invalid_class, data = mock_adlb),
    regexp = "`gg_plt` should be a plot generated by"
  )
})

test_that("annotate_lineplot_df aborts if x or y variables cannot be resolved", {
  # Without explicit variables or plot mappings, it should abort
  expect_error(
    annotate_lineplot_df(gg_plt = p_empty, data = mock_adlb),
    regexp = "Missing variables. Specify `x` and `y`"
  )
})

test_that("annotate_lineplot_df successfully extracts variables and builds the table (Default Stats)", {
  # Since p_valid has x=AVISIT, y=AVAL, and colour=ARM, it should extract them automatically
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb
    )
  )

  # The alignment engine uses cowplot, which ultimately returns a ggplot/gtable hybrid
  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df respects explicitly provided variable names", {
  # Provide the variables directly rather than relying on the plot mapping
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      x = "AVISIT",
      y = "AVAL",
      group = "ARM"
    )
  )

  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df builds correctly with custom summary statistics", {
  # Test with Median and IQR to hit the alternate stat mapping paths
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      summary_stats = c("median", "iqr")
    )
  )

  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df errors on invalid summary stats", {
  expect_error(
    annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      summary_stats = "made_up_stat" # Must be completely invalid to trigger match.arg error
    ),
    regexp = "should be one of"
  )
})
