# --- Mock Data & Setup ---

# 1. Create a dummy dataset
mock_adlb <- data.frame(
  AVISIT = rep(c(0, 4, 8), each = 4),
  AVAL = c(
    10, 12, 11, 13, # Visit 0
    14, 15, 14, 16, # Visit 4
    18, 19, 17, 20 # Visit 8
  ),
  ARM = rep(c("Trt A", "Trt B"), times = 6)
)

# 2. Create a properly classed base plot (Mocking gg_lineplot output)
p_valid <- ggplot2::ggplot(mock_adlb, ggplot2::aes(x = AVISIT, y = AVAL, colour = ARM)) +
  ggplot2::geom_line() +
  ggplot2::geom_point()
class(p_valid) <- c("crane_gg_line", class(p_valid))

# 3. Create a non-classed base plot to test warnings
p_invalid_class <- ggplot2::ggplot(mock_adlb, ggplot2::aes(x = AVISIT, y = AVAL, colour = ARM)) +
  ggplot2::geom_line()

# 4. Create an empty plot to test missing variable aborts
p_empty <- ggplot2::ggplot()
class(p_empty) <- c("crane_gg_line", class(p_empty))


# --- Tests ---

test_that("annotate_lineplot_df warns if plot is not generated by gg_lineplot", {
  # Expect the specific cli_warn message
  expect_warning(
    annotate_lineplot_df(gg_plt = p_invalid_class, data = mock_adlb),
    regexp = "`gg_plt` should be a plot generated by"
  )
})

test_that("annotate_lineplot_df aborts if x or y variables cannot be resolved", {
  # Without explicit variables or plot mappings, it should abort
  expect_error(
    annotate_lineplot_df(gg_plt = p_empty, data = mock_adlb),
    regexp = "Missing variables. Specify `x` and `y`"
  )
})

test_that("annotate_lineplot_df successfully extracts variables and builds the table (Default Stats)", {
  # Since p_valid has x=AVISIT, y=AVAL, and colour=ARM, it should extract them automatically
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb
    )
  )

  # The alignment engine uses cowplot, which ultimately returns a ggplot/gtable hybrid
  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df respects explicitly provided variable names", {
  # Provide the variables directly rather than relying on the plot mapping
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      x = "AVISIT",
      y = "AVAL",
      group = "ARM"
    )
  )

  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df builds correctly with custom summary statistics", {
  # Test with Median and IQR to hit the alternate stat mapping paths
  expect_no_error(
    res <- annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      summary_stats = c("median", "iqr")
    )
  )

  expect_s3_class(res, "ggplot")
})

test_that("annotate_lineplot_df errors on invalid summary stats", {
  expect_error(
    annotate_lineplot_df(
      gg_plt = p_valid,
      data = mock_adlb,
      summary_stats = "made_up_stat" # Must be completely invalid to trigger match.arg error
    ),
    regexp = "should be one of"
  )
})

test_that("annotate_lineplot_df formats numeric digits correctly", {
  # 1. Mock df2gg_aligned to intercept the data frame before plotting
  mock_df2gg <- function(df, ...) {
    return(df) # Return the data frame instead of generating the ggplot
  }

  # 2. Run the function using the mocked binding
  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("n", "mean", "sd"),
        digits = c(0, 2, 2) # n = 0, mean = 2, sd = 2
      )
    },
    df2gg_aligned = mock_df2gg
  )

  # 3. Verify we intercepted the data frame
  expect_s3_class(res_df, "data.frame")

  # 4. Extract Visit '0' values for n, Mean, and SD from the first treatment group
  # (Using trimws() ensures we don't fail due to hidden trailing spaces)
  val_n <- trimws(res_df[grepl("n$", trimws(res_df$Group)), "0"][1])
  val_mean <- trimws(res_df[grepl("Mean$", trimws(res_df$Group)), "0"][1])
  val_sd <- trimws(res_df[grepl("SD$", trimws(res_df$Group)), "0"][1])

  # 5. Assertions using Regular Expressions

  # Check 'n' has NO decimal point (e.g., "2" not "2.0")
  expect_false(grepl("\\.", val_n))

  # Check 'mean' has a decimal point followed by EXACTLY 2 digits (e.g., "10.50")
  expect_true(grepl("\\.[0-9]{2}$", val_mean))

  # Check 'sd' has a decimal point followed by EXACTLY 2 digits (e.g., "0.71")
  expect_true(grepl("\\.[0-9]{2}$", val_sd))
})

test_that("annotate_lineplot_df computes se and matches sd / sqrt(n)", {
  mock_df2gg <- function(df, ...) df

  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("n", "mean", "se"),
        digits = c(0, 4, 4)
      )
    },
    df2gg_aligned = mock_df2gg
  )

  expect_s3_class(res_df, "data.frame")

  # SE row is present and labelled
  expect_true(any(grepl("SE$", trimws(res_df$Group))))

  # Verify Visit '0' SE equals sd / sqrt(n) for the first treatment group
  x <- mock_adlb$AVAL[mock_adlb$AVISIT == 0 & mock_adlb$ARM == "Trt A"]
  expected_se <- stats::sd(x) / sqrt(length(x))
  val_se <- trimws(res_df[grepl("SE$", trimws(res_df$Group)), "0"][1])

  expect_equal(as.numeric(val_se), expected_se, tolerance = 1e-3)
})

test_that("annotate_lineplot_df computes ci and matches a t-based interval", {
  mock_df2gg <- function(df, ...) df

  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("n", "mean", "ci"),
        conf_level = 0.95
      )
    },
    df2gg_aligned = mock_df2gg
  )

  expect_s3_class(res_df, "data.frame")

  # The CI row is labelled with the confidence level
  expect_true(any(grepl("95% CI", trimws(res_df$Group))))

  # Verify Visit '0' CI equals the t interval for the first treatment group
  x <- mock_adlb$AVAL[mock_adlb$AVISIT == 0 & mock_adlb$ARM == "Trt A"]
  n <- length(x)
  err <- stats::qt(0.975, df = n - 1) * stats::sd(x) / sqrt(n)
  expected <- c(mean(x) - err, mean(x) + err)

  val_ci <- res_df[grepl("95% CI$", trimws(res_df$Group)), "0"][1]
  # gtsummary separates the bounds with a non-breaking space; strip all
  # non-numeric characters (except the separator and sign) before parsing
  nums <- regmatches(val_ci, gregexpr("-?[0-9.]+", val_ci))[[1]]
  got <- as.numeric(nums)

  expect_equal(got, expected, tolerance = 1e-2)
})

test_that("annotate_lineplot_df ci label follows conf_level", {
  mock_df2gg <- function(df, ...) df

  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("mean", "ci"),
        conf_level = 0.90
      )
    },
    df2gg_aligned = mock_df2gg
  )

  expect_true(any(grepl("90% CI", trimws(res_df$Group))))
})

test_that("annotate_lineplot_df mean_se reports the mean +/- 1 SE interval", {
  mock_df2gg <- function(df, ...) df

  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("n", "mean", "mean_se")
      )
    },
    df2gg_aligned = mock_df2gg
  )

  expect_s3_class(res_df, "data.frame")

  # The mean_se row carries the default label
  expect_true(any(grepl("Mean -/\\+ 1xSE", trimws(res_df$Group))))

  # Verify Visit '0' interval equals mean +/- se for the first treatment group
  x <- mock_adlb$AVAL[mock_adlb$AVISIT == 0 & mock_adlb$ARM == "Trt A"]
  se <- stats::sd(x) / sqrt(length(x))
  expected <- c(mean(x) - se, mean(x) + se)

  val_se <- res_df[grepl("1xSE$", trimws(res_df$Group)), "0"][1]
  # gtsummary separates the bounds with a non-breaking space; extract the numbers
  nums <- regmatches(val_se, gregexpr("-?[0-9.]+", val_se))[[1]]
  got <- as.numeric(nums)

  expect_equal(got, expected, tolerance = 1e-2)
})

test_that("annotate_lineplot_df mean_se label is configurable via se_label", {
  mock_df2gg <- function(df, ...) df

  res_df <- testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(
        gg_plt = p_valid,
        data = mock_adlb,
        summary_stats = c("mean", "mean_se"),
        se_label = "Mean +/- SE"
      )
    },
    df2gg_aligned = mock_df2gg
  )

  expect_true(any(grepl("Mean \\+/- SE", trimws(res_df$Group))))
})

test_that("annotate_lineplot_df forwards font_size to df2gg_aligned", {
  captured <- NULL
  mock_df2gg <- function(df, ..., text_size, label_size) {
    captured <<- list(text_size = text_size, label_size = label_size)
    df
  }

  testthat::with_mocked_bindings(
    {
      annotate_lineplot_df(gg_plt = p_valid, data = mock_adlb, font_size = 14)
    },
    df2gg_aligned = mock_df2gg
  )

  expect_equal(captured$label_size, 14)
  expect_equal(captured$text_size, 14 / ggplot2::.pt)
})
