#' Add Difference Row to tbl_survfit_times (Legacy)
#'
#' @description
#' This function is maintained as a legacy method to provide a clear migration
#' path for existing scripts. Because the architecture of `tbl_survfit_times()`
#' was decoupled to separate data extraction from table rendering, it is no
#' longer possible to automatically compute survival differences from the
#' rendered table object. Users should transition to `get_surv_diff_df()`.
#'
#' @param x (`tbl_survfit_times`)\cr
#'   A table object generated by `tbl_survfit_times()`.
#' @param ... Additional arguments passed to other methods.
#'
#' @return Defunct; throws an error with migration instructions directing users
#'   to `get_surv_diff_df()`.
#'
#' @method add_difference_row tbl_survfit_times
#' @export
add_difference_row.tbl_survfit_times <- function(x, ...) {
  # The table object no longer stores raw data or model formulas.
  # We abort with a highly specific migration path directing the user
  # to the new get_surv_diff_df() extractor to fit the decoupled design.
  rlang::abort(
    paste(
      "`add_difference_row()` is defunct for `tbl_survfit_times`.",
      "Since the architecture was decoupled, the table object no longer",
      "contains the raw data required to calculate survival differences.",
      "Please use the new `get_surv_diff_df()` function to extract difference",
      "statistics, bind those rows to your survival dataframe using",
      "`dplyr::bind_rows()`, and then render the final `tbl_survfit_times()`."
    )
  )
}
