#' @title Annotate Line Plot with Summary Table
#'
#' @description Aligns and appends a `gtsummary`-generated statistics table
#'   beneath a standard line plot using `cowplot`.
#'
#' @param gg_plt (`ggplot2`)\cr
#'   The base line plot generated by `gg_lineplot()`.
#' @param data (`data.frame`)\cr
#'   The raw data used to generate the statistics.
#' @param x,y,group (`string` or `NULL`)\cr
#'   Optional column names as strings. If `NULL` (default), the function
#'   automatically extracts these from the `gg_plt` mapping.
#' @param summary_stats (`character`)\cr
#'   Vector of statistics to include. Defaults to `c("n", "mean", "sd")`.
#' @param rel_height_plot (`numeric`)\cr
#'   Relative height of the plot vs the table. Defaults to `0.75`.
#'
#' @return A `cowplot` object.
#'
#' @examples
#' # 1. Create a mock dataset
#' set.seed(123)
#' mock_adlb <- data.frame(
#'   ARM = rep(c("Treatment A", "Treatment B"), each = 30),
#'   AVISIT = rep(c(0, 4, 8), 20),
#'   AVAL = rnorm(60, mean = 10, sd = 2)
#' )
#'
#' # 2. Generate the base line plot
#' p_base <- gg_lineplot_2(
#'   data = mock_adlb,
#'   x = AVISIT,
#'   y = AVAL,
#'   group = ARM
#' )
#'
#' # 3. Annotate with default stats (auto-extracts variables from p_base)
#' annotate_lineplot_df(gg_plt = p_base, data = mock_adlb)
#'
#' # 4. Annotate with custom statistics (Median and IQR)
#' annotate_lineplot_df(
#'   gg_plt = p_base,
#'   data = mock_adlb,
#'   summary_stats = c("n", "median", "iqr")
#' )
#'
#' @export
annotate_lineplot_df <- function(gg_plt,
                                 data,
                                 x = NULL,
                                 y = NULL,
                                 group = NULL,
                                 summary_stats = c("n", "mean", "sd"),
                                 rel_height_plot = 0.75) {
  if (!inherits(gg_plt, "crane_gg_line")) {
    cli::cli_warn(c(
      "!" = "`gg_plt` should be a plot generated by {.fun gg_lineplot}."
    ))
  }

  # Auto-extract variable names from the ggplot mapping if not explicitly provided
  if (is.null(x)) x <- gg_varname_extraction(gg_plt$mapping$x)
  if (is.null(y)) y <- gg_varname_extraction(gg_plt$mapping$y)
  if (is.null(group)) group <- gg_varname_extraction(gg_plt$mapping$colour)

  if (any(vapply(list(x, y), is.null, logical(1)))) {
    cli::cli_abort(
      paste0(
        "Missing variables. Specify {.arg x} and {.arg y},",
        "or ensure they are mapped in the plot."
      )
    )
  }

  stat_syntax <- c(
    "n" = "{N_nonmiss}",
    "mean" = "{mean}",
    "sd" = "{sd}",
    "median" = "{median}",
    "iqr" = "{p25}, {p75}"
  )

  stat_labels <- c(
    "n" = "n",
    "mean" = "Mean",
    "sd" = "SD",
    "median" = "Median",
    "iqr" = "IQR"
  )

  summary_stats <- match.arg(
    summary_stats,
    choices = names(stat_syntax),
    several.ok = TRUE
  )

  gts_stat <- stat_syntax[summary_stats]
  gts_stat_labels <- stat_labels[summary_stats]

  # Compute statistics across timepoints utilizing gtsummary
  gts_tbl <- data |>
    dplyr::mutate(..time_factor.. = as.factor(.data[[x]])) |>
    gtsummary::tbl_strata(
      strata = if (!is.null(group)) dplyr::all_of(group) else NULL,
      .combine_with = "tbl_stack",
      .tbl_fun = ~ .x |>
        gtsummary::tbl_summary(
          by = "..time_factor..",
          include = dplyr::all_of(y),
          type = list(dplyr::all_of(y) ~ "continuous2"),
          statistic = list(dplyr::all_of(y) ~ gts_stat),
          missing = "no",
          label = list(dplyr::all_of(y) ~ " ")
        ) |>
        gtsummary::add_stat_label(label = dplyr::all_of(y) ~ gts_stat_labels) |>
        gtsummary::modify_header(gtsummary::all_stat_cols() ~ "{level}")
    ) |>
    gtsummary::modify_header(label = "remove")

  # Format into a clean data frame for alignment
  formatted_df <- as.data.frame(gtsummary::as_tibble(gts_tbl, col_labels = TRUE))
  formatted_df[is.na(formatted_df)] <- ""
  names(formatted_df) <- gsub("\\*", "", names(formatted_df))

  strata_col_name <- names(formatted_df)[1]

  formatted_df <- formatted_df |>
    dplyr::mutate(Group = paste0(.data[[strata_col_name]], .data[["remove"]])) |>
    dplyr::select(-remove)

  raw_labels <- as.character(formatted_df[[1]])
  is_stat <- trimws(raw_labels) %in% c("n", "Mean", "SD", "Median", "IQR")

  # Apply Plotmath styling (bold for headers, indent for stats)
  y_labels <- parse(text = ifelse(
    is_stat,
    paste0('~~~~"', trimws(raw_labels), '"'),
    paste0('bold("', trimws(raw_labels), '")')
  ))

  # Finally, pass to the alignment engine
  df2gg_aligned(
    df = formatted_df,
    gg_plt = gg_plt,
    show_xaxis = FALSE,
    type = "GEN",
    y_labels = y_labels,
    rel_height_plot = rel_height_plot
  )
}
