#' Annotate PK Plot with Summary Table
#'
#' @description
#' These functions provide capabilities to annotate Pharmacokinetics plot
#'  ([gg_pkc_lineplot()]) with additional summary statistics table.
#' The annotations are added using the `cowplot` package for flexible placement.
#'
#' @param gg_plt (`ggplot2`)\cr
#'   The PK plot.
#' @param data (`data.frame`)\cr
#'   The raw or summarized dataset used to generate the table.
#' @param time_var,analyte_var,group ([`tidy-select`][dplyr::dplyr_tidy_select])\cr
#'   Optional. If `NULL` (default), the function automatically extracts these
#'   from the `gg_plt` mapping.
#' @param summary_stats (`character`)\cr
#'   A vector of statistics to include. Defaults to `c("n", "mean", "sd")`.
#' @param digits (`numeric`, `list`, or `formula`)\cr
#'   Optional specification for the number of decimal places for the summary statistics.
#'   Can be a single integer (e.g., `2`), a vector of integers matching the statistics
#'   (e.g., `c(0, 2, 2)`), or a `gtsummary` style formula. Defaults to `NULL`
#'   (uses `gtsummary` default auto-formatting).
#' @param text_size (`numeric`)\cr
#'   The font size for the table text. Defaults to `3.5`.
#' @param rel_height_plot (`numeric`)\cr
#'   Relative height of the plot vs the table. Defaults to `0.75`.
#'
#' @seealso [gg_pkc_lineplot()] for related functionalities.
#' @examples
#' # Prepare PK Data using the built-in Theoph dataset
#' df_pk <- Theoph
#' df_pk$Time_Nominal <- round(df_pk$Time)
#' # Filter to specific timepoints to keep the table clean
#' df_pk <- df_pk[df_pk$Time_Nominal %in% c(0, 2, 4, 8, 24), ]
#' # Create a mock treatment group based on Dose
#' df_pk$Dose_Group <- ifelse(df_pk$Dose > 4.5, "High Dose", "Low Dose")
#'
#' # Create the Base Plot using actual Theoph column names
#' p_pk <- gg_pkc_lineplot(
#'   data = df_pk,
#'   time_var = Time_Nominal,
#'   analyte_var = conc,
#'   group = Dose_Group,
#'   stat = "mean",
#'   variability = "sd",
#'   log_y = FALSE
#' )
#'
#' # Annotate the Plot (Auto-detects variables from aesthetic mapping)
#' annotate_pkc_df(
#'   data = df_pk,
#'   gg_plt = p_pk
#' )
#'
#' # Annotate with specific statistics, explicit variable names, and explicit digits
#' annotate_pkc_df(
#'   data = df_pk,
#'   gg_plt = p_pk,
#'   time_var = "Time_Nominal",
#'   analyte_var = "conc",
#'   group = "Dose_Group",
#'   summary_stats = c("n", "median", "iqr"),
#'   digits = c(0, 2, 2)
#' )
#' @export
annotate_pkc_df <- function(gg_plt,
                            data,
                            time_var = NULL,
                            analyte_var = NULL,
                            group = NULL,
                            summary_stats = c("n", "mean", "sd"),
                            digits = NULL,
                            text_size = 3.5,
                            rel_height_plot = 0.75) {
  # 1. Input Validation---------------------------------------------------------
  if (!inherits(gg_plt, "crane_gg_pkc")) {
    cli::cli_warn(c(
      "!" = "`gg_plt` should be a plot generated by {.fun gg_pkc_lineplot}.",
      "i" = paste0(
        "This function was specifically designed to annotate PK line plots. ",
        "It might not provide adequate results for other type of plots."
      )
    ))
  }

  if (is.null(time_var)) time_var <- gg_varname_extraction(gg_plt$mapping$x)
  if (is.null(analyte_var)) analyte_var <- gg_varname_extraction(gg_plt$mapping$y)
  if (is.null(group)) group <- gg_varname_extraction(gg_plt$mapping$colour)

  if (any(vapply(list(time_var, analyte_var, group), is.null, logical(1)))) {
    cli::cli_abort(
      paste0(
        "Missing variables. Specify {.arg time_var}, ",
        "{.arg analyte_var}, and {.arg group}."
      )
    )
  }

  # 2. Stat Setup---------------------------------------------------------------
  stat_syntax <- c(
    "n" = "{N_nonmiss}",
    "mean" = "{mean}",
    "sd" = "{sd}",
    "median" = "{median}",
    "iqr" = "{p25}, {p75}"
  )
  stat_labels <- c(
    "n" = "n",
    "mean" = "Mean",
    "sd" = "SD",
    "median" = "Median",
    "iqr" = "IQR"
  )

  summary_stats <- match.arg(
    summary_stats,
    choices = names(stat_syntax),
    several.ok = TRUE
  )
  gts_stat <- stat_syntax[summary_stats]
  gts_stat_labels <- stat_labels[summary_stats]

  # Format digits argument for gtsummary
  gts_digits <- if (!is.null(digits) && is.numeric(digits)) {
    list(dplyr::all_of(analyte_var) ~ digits)
  } else {
    digits # Allows advanced users to pass standard gtsummary list/formulas directly
  }

  # 3. Table Generation---------------------------------------------------------
  gts_tbl <- data |>
    dplyr::mutate(..time_factor.. = as.factor(.data[[time_var]])) |>
    gtsummary::tbl_strata(
      strata = dplyr::all_of(group),
      .combine_with = "tbl_stack",
      .tbl_fun = ~ .x |>
        tbl_roche_summary(
          by = "..time_factor..",
          include = dplyr::all_of(analyte_var),
          type = list(dplyr::all_of(analyte_var) ~ "continuous2"),
          statistic = list(dplyr::all_of(analyte_var) ~ gts_stat),
          nonmissing = "no",
          label = list(dplyr::all_of(analyte_var) ~ " "),
          digits = gts_digits
        ) |>
        gtsummary::add_stat_label(
          label = dplyr::all_of(analyte_var) ~ gts_stat_labels
        ) |>
        gtsummary::modify_header(gtsummary::all_stat_cols() ~ "{level}")
    ) |>
    gtsummary::modify_header(label = "remove")

  # 4. Cleanup with Positional Fix----------------------------------------------
  formatted_df <- as.data.frame(
    gtsummary::as_tibble(gts_tbl, col_labels = TRUE)
  )
  formatted_df[is.na(formatted_df)] <- ""
  names(formatted_df) <- gsub("\\*", "", names(formatted_df))

  strata_col_name <- names(formatted_df)[1]

  formatted_df <- formatted_df |>
    dplyr::mutate(
      Group = paste0(.data[[strata_col_name]], .data[["remove"]])
    ) |>
    dplyr::select(-remove)

  # 5. Format Labels using plotmath---------------------------------------------
  raw_labels <- as.character(formatted_df[[1]])
  is_stat <- trimws(raw_labels) %in% c("n", "Mean", "SD", "Median", "IQR")

  pk_y_labels <- parse(text = ifelse(
    is_stat,
    paste0('~~~~"', trimws(raw_labels), '"'),
    paste0('bold("', trimws(raw_labels), '")')
  ))

  # 6. Table Plotting-----------------------------------------------------------
  gg_table <- df2gg_aligned(
    df = formatted_df,
    gg_plt = gg_plt,
    show_xaxis = FALSE,
    type = "PK",
    y_labels = pk_y_labels,
    rel_height_plot = rel_height_plot
  )

  gg_table
}
