#' Annotate Line Plot with Summary Table
#'
#' @description
#' These functions provide capabilities to annotate lineplot
#' ([gg_lineplot()]) with additional summary statistics table.
#' The annotations are added using the `cowplot` package for flexible placement.
#'
#' @param gg_plt (`ggplot2`)\cr
#'   The base line plot generated by `gg_lineplot()`.
#' @param data (`data.frame`)\cr
#'   The raw data used to generate the statistics.
#' @param x,y,group (`string` or `NULL`)\cr
#'   Optional column names as strings. If `NULL` (default), the function
#'   automatically extracts these from the `gg_plt` mapping.
#' @param summary_stats (`character`)\cr
#'   Vector of statistics to include. One or more of `"n"`, `"mean"`, `"sd"`,
#'   `"se"`, `"mean_se"`, `"ci"`, `"median"`, and `"iqr"`. Defaults to
#'   `c("n", "mean", "sd")`. `"se"` reports the standard error on its own, while
#'   `"mean_se"` reports the mean +/- 1 standard error interval (matching the
#'   error bars drawn by `gg_lineplot(variability = "se")`). `"ci"` reports the
#'   confidence interval of the mean at `conf_level`.
#' @param conf_level (`numeric`)\cr
#'   Confidence level for the `"ci"` statistic. Defaults to `0.95`.
#' @param se_label (`string`)\cr
#'   Row label for the `"mean_se"` statistic. Defaults to `"Mean -/+ 1xSE"`.
#' @param labels (`character` or `NULL`)\cr
#'   Optional named vector overriding the default row labels, keyed by statistic
#'   name (`"n"`, `"mean"`, `"sd"`, `"se"`, `"mean_se"`, `"ci"`, `"median"`,
#'   `"iqr"`). For example, `labels = c(mean = "LS mean")` on an MMRM plot.
#'   Defaults to `NULL` (built-in labels).
#' @param blank_timepoints (`character` or `NULL`)\cr
#'   Optional vector of timepoint (x-axis level) labels at which the continuous
#'   statistics are blanked, while the count (`"n"`) is kept. Useful for a
#'   constant change-from-baseline visit in an MMRM plot, where the mean/SD/CI
#'   are `0` by construction and carry no information. Defaults to `NULL`.
#' @param digits (`numeric`, `list`, or `formula`)\cr
#'   Optional specification for the number of decimal places for the summary statistics.
#'   Can be a single integer (e.g., `2`), a vector of integers matching the statistics
#'   (e.g., `c(0, 2, 2)`), or a `gtsummary` style formula. Defaults to `NULL`
#'   (uses `gtsummary` default auto-formatting).
#' @param font_size (`numeric`)\cr
#'   Base font size for the summary table text. Defaults to `10`.
#' @param rel_height_plot (`numeric`)\cr
#'   Relative height of the plot vs the table. Defaults to `0.75`.
#'
#' @return A `cowplot` object.
#'
#' @seealso [gg_lineplot()] for related functionalities.
#'
#' @examples
#' # 1. Create a mock dataset
#' set.seed(123)
#' mock_adlb <- data.frame(
#'   ARM = rep(c("Treatment A", "Treatment B"), each = 30),
#'   AVISIT = rep(c(0, 4, 8), 20),
#'   AVAL = rnorm(60, mean = 10, sd = 2)
#' )
#'
#' # 2. Generate the base line plot
#' p_base <- gg_lineplot(
#'   data = mock_adlb,
#'   x = AVISIT,
#'   y = AVAL,
#'   group = ARM
#' )
#'
#' # 3. Annotate with default stats (auto-extracts variables from p_base)
#' annotate_lineplot_df(gg_plt = p_base, data = mock_adlb)
#'
#' # 4. Annotate with custom statistics and exactly 2 decimal places
#' annotate_lineplot_df(
#'   gg_plt = p_base,
#'   data = mock_adlb,
#'   summary_stats = c("n", "median", "iqr"),
#'   digits = c(0, 2, 2)
#' )
#'
#' # 5. Report the mean +/- 1 SE interval with a custom label
#' annotate_lineplot_df(
#'   gg_plt = p_base,
#'   data = mock_adlb,
#'   summary_stats = c("n", "mean", "mean_se"),
#'   se_label = "Mean +/- SE"
#' )
#'
#' # 6. Rename a statistic and blank a constant baseline column (e.g. MMRM)
#' annotate_lineplot_df(
#'   gg_plt = p_base,
#'   data = mock_adlb,
#'   summary_stats = c("n", "mean", "sd"),
#'   labels = c(mean = "LS mean"),
#'   blank_timepoints = "0"
#' )
#'
#' @export
annotate_lineplot_df <- function(gg_plt,
                                 data,
                                 x = NULL,
                                 y = NULL,
                                 group = NULL,
                                 summary_stats = c("n", "mean", "sd"),
                                 conf_level = 0.95,
                                 se_label = "Mean -/+ 1xSE",
                                 labels = NULL,
                                 blank_timepoints = NULL,
                                 digits = NULL,
                                 font_size = 10,
                                 rel_height_plot = 0.75) {
  if (!inherits(gg_plt, "crane_gg_line")) {
    cli::cli_warn(c(
      "!" = "`gg_plt` should be a plot generated by {.fun gg_lineplot}."
    ))
  }

  # Confidence interval bounds for the table, delegated to the same helper that
  # draws the error bars in `gg_lineplot()` so the table can never disagree with
  # the plotted interval. They are picked up by name when referenced in the
  # `{conf.low}` / `{conf.high}` glue of the `statistic` argument below.
  conf.low <- function(x) {
    .calc_stats(x, stat = "mean", variability = "ci", conf_level = conf_level)$ymin
  }
  conf.high <- function(x) {
    .calc_stats(x, stat = "mean", variability = "ci", conf_level = conf_level)$ymax
  }

  # Mean +/- 1 SE bounds for the table, delegated to the same helper that draws
  # the error bars in `gg_lineplot(variability = "se")` so the reported interval
  # always matches the plot. Picked up by name in the `{se.low}` / `{se.high}`
  # glue of the `"mean_se"` statistic below.
  se.low <- function(x) {
    .calc_stats(x, stat = "mean", variability = "se", conf_level = conf_level)$ymin
  }
  se.high <- function(x) {
    .calc_stats(x, stat = "mean", variability = "se", conf_level = conf_level)$ymax
  }

  # Auto-extract variable names from the ggplot mapping if not explicitly provided
  if (is.null(x)) x <- gg_varname_extraction(gg_plt$mapping$x)
  if (is.null(y)) y <- gg_varname_extraction(gg_plt$mapping$y)
  if (is.null(group)) group <- gg_varname_extraction(gg_plt$mapping$colour)

  if (any(vapply(list(x, y), is.null, logical(1)))) {
    cli::cli_abort(
      paste0(
        "Missing variables. Specify {.arg x} and {.arg y},",
        "or ensure they are mapped in the plot."
      )
    )
  }

  stat_syntax <- c(
    "n" = "{N_nonmiss}",
    "mean" = "{mean}",
    "sd" = "{sd}",
    "se" = "{se}",
    "mean_se" = "{se.low}, {se.high}",
    "ci" = "{conf.low}, {conf.high}",
    "median" = "{median}",
    "iqr" = "{p25}, {p75}"
  )

  ci_label <- paste0(round(conf_level * 100), "% CI")
  stat_labels <- c(
    "n" = "n",
    "mean" = "Mean",
    "sd" = "SD",
    "se" = "SE",
    "mean_se" = se_label,
    "ci" = ci_label,
    "median" = "Median",
    "iqr" = "IQR"
  )

  # Override any default row labels with user-supplied ones, e.g.
  # `labels = c(mean = "LS mean")` for an MMRM plot.
  if (!is.null(labels)) {
    if (is.null(names(labels)) || any(names(labels) == "")) {
      cli::cli_abort("{.arg labels} must be a named vector, e.g. {.code c(mean = \"LS mean\")}.")
    }
    unknown <- setdiff(names(labels), names(stat_labels))
    if (length(unknown) > 0) {
      cli::cli_abort(c(
        "Unknown statistic{?s} in {.arg labels}: {.val {unknown}}.",
        "i" = "Valid names are {.val {names(stat_labels)}}."
      ))
    }
    stat_labels[names(labels)] <- labels
  }

  summary_stats <- match.arg(
    summary_stats,
    choices = names(stat_syntax),
    several.ok = TRUE
  )

  gts_stat <- stat_syntax[summary_stats]
  gts_stat_labels <- stat_labels[summary_stats]

  # Format digits argument for gtsummary
  gts_digits <- if (!is.null(digits) && is.numeric(digits)) {
    list(dplyr::all_of(y) ~ digits)
  } else {
    digits # Allows advanced users to pass standard gtsummary list/formulas directly
  }

  # Compute statistics across timepoints utilizing gtsummary
  gts_tbl <- data |>
    dplyr::mutate(..time_factor.. = as.factor(.data[[x]])) |>
    gtsummary::tbl_strata(
      strata = if (!is.null(group)) dplyr::all_of(group) else NULL,
      .combine_with = "tbl_stack",
      .tbl_fun = ~ .x |>
        tbl_roche_summary(
          by = "..time_factor..",
          include = dplyr::all_of(y),
          type = list(dplyr::all_of(y) ~ "continuous2"),
          statistic = list(dplyr::all_of(y) ~ gts_stat),
          nonmissing = "no",
          label = list(dplyr::all_of(y) ~ " "),
          digits = gts_digits
        ) |>
        gtsummary::add_stat_label(label = dplyr::all_of(y) ~ gts_stat_labels) |>
        gtsummary::modify_header(gtsummary::all_stat_cols() ~ "{level}")
    ) |>
    gtsummary::modify_header(label = "remove")

  # Format into a clean data frame for alignment
  formatted_df <- as.data.frame(gtsummary::as_tibble(gts_tbl, col_labels = TRUE))
  formatted_df[is.na(formatted_df)] <- ""
  names(formatted_df) <- gsub("\\*", "", names(formatted_df))

  strata_col_name <- names(formatted_df)[1]

  formatted_df <- formatted_df |>
    dplyr::mutate(Group = paste0(.data[[strata_col_name]], .data[["remove"]])) |>
    dplyr::select(-remove)

  raw_labels <- as.character(formatted_df[[1]])
  is_stat <- trimws(raw_labels) %in% trimws(gts_stat_labels)

  # Blank the continuous statistics at fixed timepoints (e.g. a constant-zero
  # change-from-baseline visit in an MMRM plot), where a "0.00" mean/SD/CI is an
  # artifact of the constant rather than a real estimate. The count ("n") is a
  # genuine value and is kept.
  if (!is.null(blank_timepoints)) {
    missing_tp <- setdiff(blank_timepoints, names(formatted_df))
    if (length(missing_tp) > 0) {
      cli::cli_warn(c(
        "!" = "Timepoint{?s} in {.arg blank_timepoints} not found: {.val {missing_tp}}.",
        "i" = "Available timepoint columns are {.val {setdiff(names(formatted_df), c(names(formatted_df)[1], 'Group'))}}."
      ))
    }
    n_label <- trimws(stat_labels[["n"]])
    blank_rows <- is_stat & trimws(raw_labels) != n_label
    for (tp in intersect(blank_timepoints, names(formatted_df))) {
      formatted_df[blank_rows, tp] <- ""
    }
  }

  # Apply Plotmath styling (bold for headers, indent for stats)
  y_labels <- parse(text = ifelse(
    is_stat,
    paste0('~~~~"', trimws(raw_labels), '"'),
    paste0('bold("', trimws(raw_labels), '")')
  ))

  # Finally, pass to the alignment engine
  df2gg_aligned(
    df = formatted_df,
    gg_plt = gg_plt,
    show_xaxis = FALSE,
    type = "GEN",
    y_labels = y_labels,
    text_size = font_size / ggplot2::.pt,
    label_size = font_size,
    rel_height_plot = rel_height_plot
  )
}
