#' Pairwise Cox Proportional Hazards Table
#'
#' @description
#' Generates a `gtsummary` table from the pairwise comparison results created by
#' `get_cox_pairwise_df()`. The table splits the results by comparison arms,
#' presenting the p-value, Hazard Ratio, and 95% Confidence Interval in a
#' stacked layout where statistics form the rows of the table.
#'
#' @param pairwise_df (`data.frame`)\cr
#'   The results `data.frame` output generated by `get_cox_pairwise_df()`.
#'   Must contain rownames (comparison arms) and at least one statistic column:
#'   `"HR"`, `"95% CI"`, or `"p-value (...)"`.
#'
#' @return A `gtsummary` object with additional class `tbl_coxph`.
#'
#' @seealso `get_cox_pairwise_df()`.
#'
#' @examplesIf requireNamespace("survival", quietly = TRUE)
#' # Setup sample survival data
#' library(survival)
#' surv_data <- lung |>
#'   dplyr::mutate(
#'     arm = factor(sample(c("A", "B", "C"), dplyr::n(), replace = TRUE)),
#'     status = status - 1
#'   ) |>
#'   dplyr::filter(dplyr::if_all(dplyr::everything(), ~ !is.na(.)))
#'
#' formula <- Surv(time, status) ~ arm
#'
#' # Generate the pairwise statistics data.frame
#' pairwise_results <- get_cox_pairwise_df(
#'   model_formula = formula,
#'   data = surv_data,
#'   arm = "arm",
#'   ref_group = "A"
#' )
#'
#' # Example 1: Full table
#' tbl_coxph(pairwise_df = pairwise_results)
#'
#' # Example 2: Table with only HR and CI (p-value removed)
#' pairwise_no_pval <- pairwise_results[, c("HR", "95% CI"), drop = FALSE]
#' tbl_coxph(pairwise_df = pairwise_no_pval)
#'
#' # Example 3: Table with only p-values
#' pairwise_only_pval <- pairwise_results[, 3, drop = FALSE]
#' tbl_coxph(pairwise_df = pairwise_only_pval)
#'
#' # Example 4: Customize p-value precision
#' # Pre-format the p-value column as character before passing to tbl_coxph().
#' # Character values are displayed as-is (no further formatting applied).
#' pval_col <- grep("p-value", names(pairwise_results), value = TRUE)
#' custom <- pairwise_results
#' custom[[pval_col]] <- ifelse(
#'   custom[[pval_col]] < 0.001, "<0.001",
#'   sprintf("%.3f", custom[[pval_col]])
#' )
#' tbl_coxph(pairwise_df = custom)
#'
#' @export
tbl_coxph <- function(pairwise_df) {
  set_cli_abort_call()

  # Input Checks
  if (!is.data.frame(pairwise_df)) {
    cli::cli_abort(
      "{.arg pairwise_df} must be a {.cls data.frame}.",
      call = get_cli_abort_call()
    )
  }

  # Dynamically identify which columns are present
  has_hr <- "HR" %in% names(pairwise_df)
  has_ci <- "95% CI" %in% names(pairwise_df)

  pval_col <- grep("p-value", names(pairwise_df), value = TRUE)
  has_pval <- length(pval_col) > 0
  pval_label <- if (has_pval) pval_col[1] else NULL

  # Ensure at least one statistic column exists
  if (!has_hr && !has_ci && !has_pval) {
    cli::cli_abort(
      paste0(
        "At least one statistic column ({.val HR}, {.val 95% CI}, or ",
        "{.val p-value}) must be present in {.arg pairwise_df}."
      ),
      call = get_cli_abort_call()
    )
  }

  # Build the base tidy data frame using rownames
  df_tidy <- tibble::tibble(
    comparison_label = rownames(pairwise_df)
  )

  # Conditionally attach the formatted columns
  if (has_hr) {
    df_tidy$hr_formatted <- pairwise_df[["HR"]]
  }
  if (has_ci) {
    df_tidy$ci_formatted <- pairwise_df[["95% CI"]]
  }
  if (has_pval) {
    df_tidy$pval_formatted <- .format_pvalue(pairwise_df[[pval_label]])
  }

  # Route to single or stratified table builder based on group count
  if (nrow(df_tidy) == 1) {
    res <- .get_single_comp_table(df_tidy, pval_label = pval_label)
  } else {
    res <- df_tidy |>
      gtsummary::tbl_strata(
        strata = "comparison_label",
        .combine_with = "tbl_stack",
        .header = "{strata}",
        .tbl_fun = ~ .get_single_comp_table(.x, pval_label = pval_label)
      ) |>
      gtsummary::modify_header(groupname_col = " ")
  }

  # Final polish on the combined top-level headers
  res <- res |>
    gtsummary::modify_header(label = "")

  class(res) <- c("tbl_coxph", class(res))

  res
}

#' Build Single Comparison Table for Cox PH
#'
#' @description
#' Internal helper function to build a formatted `gtsummary` table for a single
#' comparison arm. It conditionally extracts available statistics from the
#' subsetted data and stacks them into rows for the final display.
#'
#' @param data_subset (`data.frame`)\cr
#'   A pre-processed data frame containing the formatted statistics for exactly
#'   one treatment comparison.
#' @param pval_label (`character` or `NULL`)\cr
#'   The dynamic string to use for the p-value label (e.g., "p-value (Log-rank)")
#'
#' @return A `gtsummary` object containing the stacked summary statistics.
#'
#' @keywords internal
#' @examples
#' tbl <- tibble::tibble(comparison_label = "A-B",
#'    hr_formatted = "5.21",
#'    ci_formatted = "0.25-0.35",
#'    pval_formatted = 0.005
#' )
#' .get_single_comp_table(tbl, pval_label = "p-val")
.get_single_comp_table <- function(data_subset, pval_label = NULL) {
  # Check which pre-formatted columns made it into the subset
  has_pval <- "pval_formatted" %in% names(data_subset)
  has_hr <- "hr_formatted" %in% names(data_subset)
  has_ci <- "ci_formatted" %in% names(data_subset)

  # Dynamically build the inclusion list and the label mapping
  vars_include <- c()
  label_list <- list()

  if (has_pval) {
    vars_include <- c(vars_include, "pval_formatted")
    label_list <- c(label_list, list(pval_formatted ~ pval_label))
  }
  if (has_hr) {
    vars_include <- c(vars_include, "hr_formatted")
    label_list <- c(label_list, list(hr_formatted ~ "Hazard Ratio"))
  }
  if (has_ci) {
    vars_include <- c(vars_include, "ci_formatted")
    label_list <- c(label_list, list(ci_formatted ~ "95% CI"))
  }

  # Build a proper ARD-backed gtsummary object. We use ard_mvsummary() with a
  # trivial statistic (extract the first value) because the strings are already
  # formatted by get_cox_pairwise_df(). This lets tbl_ard_summary() render them
  # while keeping the ARD lineage for gather_ard() and downstream tooling.
  res <- data_subset |>
    cards::ard_mvsummary(
      variables = dplyr::all_of(vars_include),
      by = NULL,
      statistic = ~ list(
        my_stat = \(x, ...) x[1]
      )
    ) |>
    gtsummary::tbl_ard_summary(
      include = dplyr::all_of(vars_include),
      type = list(gtsummary::everything() ~ "continuous"),
      statistic = list(gtsummary::everything() ~ "{my_stat}"),
      label = label_list,
      missing = "no"
    ) |>
    gtsummary::modify_header(
      gtsummary::all_stat_cols() ~ " "
    ) |>
    gtsummary::modify_footnote(gtsummary::everything() ~ NA)

  # Only attempt to indent the Confidence Interval if it exists
  if (has_ci) {
    res <- res |>
      gtsummary::modify_indent(
        columns = "label",
        rows = .data$variable == "ci_formatted",
        indent = 4L
      )
  }

  res
}

#' Format p-values for display
#'
#' Numeric values below 0.0001 are shown as `"<0.0001"`, others are formatted
#' to four decimal places. Character input is returned as-is, allowing users
#' to pre-format the p-value column in `pairwise_df` before calling
#' [tbl_coxph()].
#'
#' @param x (`numeric` or `character`)\cr vector of p-values.
#'
#' @returns A character vector of formatted p-values.
#' @keywords internal
#' @examples
#' .format_pvalue(0.000156)
.format_pvalue <- function(x) {
  if (is.character(x)) {
    return(x)
  }
  dplyr::case_when(
    is.na(x) ~ NA_character_,
    x < 0.0001 ~ "<0.0001",
    TRUE ~ sprintf("%.4f", x)
  )
}
