#' Create a gtsummary Table of Survival Times
#'
#' @description
#' Generates a `gtsummary` table from the survival times `data.frame` created by
#' `get_surv_times_df()`. The table dynamically adapts to whichever columns the
#' user leaves in the data frame, allowing for easy customization.
#'
#' @param surv_df (`data.frame`)\cr
#'   The results `data.frame` generated by `get_surv_times_df()`.
#'
#' @return A `gtsummary` object.
#'
#' @examples
#' library(survival)
#' surv_data <- lung
#' surv_data$status <- surv_data$status - 1
#'
#' # Example: Replicating "add_overall" functionality.
#' # 1. Fit the stratified model and extract data
#' fit_strat <- survfit(Surv(time, status) ~ sex, data = surv_data)
#' df_strat <- get_surv_times_df(fit_strat, times = c(100, 200))
#'
#' # 2. Fit the overall unstratified model and extract data
#' fit_overall <- survfit(Surv(time, status) ~ 1, data = surv_data)
#' df_overall <- get_surv_times_df(fit_overall, times = c(100, 200))
#'
#' # 3. Rename the unstratified label to "Overall" (instead of "All")
#' df_overall$Strata <- "Overall"
#'
#' # 4. Combine rows and render the single stacked table
#' combined_df <- rbind(df_overall, df_strat)
#' tbl_survfit_times(combined_df)
#'
#' @export
tbl_survfit_times <- function(surv_df) {
  if (!is.data.frame(surv_df)) {
    rlang::abort("`surv_df` must be a data.frame.")
  }

  if (!"Strata" %in% names(surv_df) || !"Time" %in% names(surv_df)) {
    rlang::abort("`surv_df` must contain at least 'Strata' and 'Time' columns.")
  }

  ci_col <- grep("% CI", names(surv_df), value = TRUE)
  has_ci <- length(ci_col) > 0

  unique_strata <- unique(surv_df$Strata)

  if (length(unique_strata) == 1) {
    res <- .get_single_time_table(
      surv_df,
      ci_col = if (has_ci) ci_col[1] else NULL
    )
  } else {
    res <- surv_df |>
      gtsummary::tbl_strata(
        strata = "Strata",
        .combine_with = "tbl_stack",
        .header = "{strata}",
        .tbl_fun = function(x) {
          .get_single_time_table(
            x,
            ci_col = if (has_ci) ci_col[1] else NULL
          )
        }
      ) |>
      gtsummary::modify_header(groupname_col = " ")
  }

  res <- res |> gtsummary::modify_header(label = "Time")

  # Ensure the object receives the correct class for S3 dispatch
  class(res) <- c("tbl_survfit_times", class(res))

  res
}

#' Build Single Strata Table for Survival Times
#' @keywords internal
#' @noRd
.get_single_time_table <- function(data_subset, ci_col = NULL) {
  data_subset$Time <- paste("Day", data_subset$Time)

  vars_include <- c()
  label_list <- list()

  if ("N at Risk" %in% names(data_subset)) {
    vars_include <- c(vars_include, "N at Risk")
    label_list <- c(label_list, list(`N at Risk` ~ "N at Risk"))
  }

  if ("Survival" %in% names(data_subset)) {
    vars_include <- c(vars_include, "Survival")
    label_list <- c(label_list, list(Survival ~ "Survival"))
  }

  if (!is.null(ci_col) && ci_col %in% names(data_subset)) {
    vars_include <- c(vars_include, ci_col)
    label_list <- c(label_list, stats::setNames(list(ci_col), ci_col))
  }

  # Capture the p-value column generated by difference tables
  if ("p-value" %in% names(data_subset)) {
    vars_include <- c(vars_include, "p-value")
    label_list <- c(label_list, list(`p-value` ~ "p-value"))
  }

  res <- data_subset |>
    cards::ard_mvsummary(
      variables = dplyr::all_of(vars_include),
      by = "Time",
      statistic = ~ list(my_stat = \(x, ...) x[1])
    ) |>
    gtsummary::tbl_ard_summary(
      by = "Time",
      type = list(gtsummary::everything() ~ "continuous"),
      statistic = list(gtsummary::everything() ~ "{my_stat}"),
      label = label_list,
      missing = "no"
    ) |>
    gtsummary::modify_header(gtsummary::all_stat_cols() ~ " ") |>
    gtsummary::modify_footnote(gtsummary::everything() ~ NA)

  # Indent the confidence interval row for better readability
  if (!is.null(ci_col)) {
    res <- res |>
      gtsummary::modify_indent(
        columns = "label",
        rows = .data$variable == ci_col,
        indent = 4L
      )
  }

  res
}
